// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef fldiffusion_h
#define fldiffusion_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win1;
#include <FL/Fl_Box.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
extern Fl_Input *form1_tab1_diffusion_filesource;
#include <FL/Fl_Button.H>
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *textdisplay1;
#include <FL/Fl_Output.H>
extern Fl_Output *win1_statusbar_content;
extern Fl_Double_Window *form2;
extern Fl_Input *form1_tab1_diffusion_plot_filesource;
Fl_Double_Window* make_window();
int main( int argc, char *argv[]);
#endif
