// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef flkeyboard_h
#define flkeyboard_h
#include <FL/Fl.H>
void addkeys();
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win;
#include <FL/Fl_Group.H>
#include <FL/Fl_Browser.H>
extern Fl_Browser *keylist;
#include <FL/Fl_Button.H>
#include <FL/Fl_Clock.H>
#include <FL/Fl_Input.H>
extern Fl_Input *selection;
Fl_Double_Window* make_window();
int main();
#endif
