// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef flmechprop_h
#define flmechprop_h
#include <FL/Fl.H>
void mycomment();

// Comment:
// ========
// For Edu

// This model is destined to use the mixture law.

// The model does not include material parameters, such 
// as grain size, dislocation density, ... composition...


#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win1;
#include <FL/Fl_Box.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
extern Fl_Input *cell_mech_1_1;
extern Fl_Input *cell_mech_1_2;
extern Fl_Input *cell_mech_1_3;
extern Fl_Input *cell_mech_3_1;
extern Fl_Input *cell_mech_3_2;
extern Fl_Input *cell_mech_3_3;
extern Fl_Input *cell_mech_4_1;
extern Fl_Input *cell_mech_4_2;
extern Fl_Input *cell_mech_4_3;
extern Fl_Input *cell_mech_5_1;
extern Fl_Input *cell_mech_5_2;
extern Fl_Input *cell_mech_5_3;
extern Fl_Input *cell_mech_6_1;
extern Fl_Input *cell_mech_6_2;
extern Fl_Input *cell_mech_6_3;
extern Fl_Input *cell_mech_7_1;
extern Fl_Input *cell_mech_7_2;
extern Fl_Input *cell_mech_7_3;
extern Fl_Input *cell_mech_8_2;
extern Fl_Input *cell_mech_8_3;
extern Fl_Input *cell_mech_8_1;
extern Fl_Input *cell_mech_2_1;
extern Fl_Input *cell_mech_2_2;
extern Fl_Input *cell_mech_2_3;
extern Fl_Input *cell_fraction_3;
extern Fl_Input *cell_fraction_4;
extern Fl_Input *cell_fraction_1;
extern Fl_Input *cell_fraction_2;
extern Fl_Input *cell_fraction_7;
extern Fl_Input *cell_fraction_8;
extern Fl_Input *cell_fraction_5;
extern Fl_Input *cell_fraction_6;
#include <FL/Fl_Button.H>
extern Fl_Input *form1_calc1_output1;
extern Fl_Input *form1_calc1_output2;
extern Fl_Input *form1_calc1_output3;
extern Fl_Input *form1_calc1_output1_f;
extern Fl_Input *form1_calc1_output2_f;
extern Fl_Input *form1_calc1_output3_f;
extern Fl_Input *form1_max_pct_f_const;
extern Fl_Input *form1_max_pct_int_step1;
extern Fl_Input *cell_fraction_1_pred;
extern Fl_Input *cell_fraction_3_pred;
extern Fl_Input *cell_fraction_4_pred;
extern Fl_Input *cell_fraction_5_pred;
extern Fl_Input *cell_fraction_6_pred;
extern Fl_Input *cell_fraction_7_pred;
extern Fl_Input *cell_fraction_8_pred;
extern Fl_Input *cell_fraction_2_pred;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *form1_tab2_frac_checker_value_f1;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f2;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f3;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f4;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f5;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f6;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f7;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f8;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f1_fixed;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f2_fixed;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f3_fixed;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f4_fixed;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f5_fixed;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f6_fixed;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f7_fixed;
extern Fl_Check_Button *form1_tab2_frac_checker_value_f8_fixed;
#include <FL/Fl_Output.H>
extern Fl_Output *win1_statusbar_content;
Fl_Double_Window* make_window();
int main( int argc, char *argv[]);
void void_user_calc_start1();
#endif
