// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef flmonitor_h
#define flmonitor_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win1;
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
Fl_Double_Window* make_window();
int main( int argc, char *argv[]);
#endif
