// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "flmonitor.h"
#include <stdio.h>
#include <stdlib.h>
#include "headerf.h"

Fl_Double_Window *win1=(Fl_Double_Window *)0;

static void cb_Quit(Fl_Button*, void*) {
  exit( 0 );
}

static void cb_1(Fl_Button*, void*) {
  system( " screen -d -m  xrandr -s 640x480   "  );
}

static void cb_2(Fl_Button*, void*) {
  system( " screen -d -m  xrandr -s 800x600   "  );
}

static void cb_4(Fl_Button*, void*) {
  system( " screen -d -m  xrandr -s 1680x1050   "  );
}

static void cb_3(Fl_Button*, void*) {
  system( " screen -d -m  xrandr -s   1366x768     "  );
}

Fl_Double_Window* make_window() {
  { win1 = new Fl_Double_Window(315, 195, "Screen");
    { Fl_Button* o = new Fl_Button(5, 170, 305, 20, "&Quit");
      o->labelfont(1);
      o->callback((Fl_Callback*)cb_Quit);
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(5, 35, 305, 125);
      o->box(FL_DOWN_BOX);
      { Fl_Button* o = new Fl_Button(10, 45, 120, 20, "&1: 640x480");
        o->callback((Fl_Callback*)cb_1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(10, 70, 120, 20, "&2: 800x600");
        o->callback((Fl_Callback*)cb_2);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(185, 70, 120, 20, "&4: 1680x1050");
        o->callback((Fl_Callback*)cb_4);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(185, 45, 120, 20, "&3: 1366x768");
        o->callback((Fl_Callback*)cb_3);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Box* o = new Fl_Box(5, 5, 305, 25, "FLMONITOR");
      o->box(FL_ENGRAVED_BOX);
      o->labelfont(1);
    } // Fl_Box* o
    win1->end();
    win1->resizable(win1);
  } // Fl_Double_Window* win1
  return win1;
}

int main( int argc, char *argv[]) {
  printf( " == FLTK == \n" );
  
  ////////////////////////////////////////////////////////
    if ( argc == 2)
    if ( strcmp( argv[1] , "" ) !=  0 )
    {
            chdir( argv[ 1 ] );
    }
  
    char mydirnow[2500];
    printf( "Current Directory: %s \n", getcwd( mydirnow, 2500 ) );
  
  
    make_window();
    win1->show();
  
    Fl::run();
}
