// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "flopencalphad.h"
#include <stdio.h>
#include <stdlib.h>
#include "ccode.h"
#include <FL/Fl_Output.H>
#include "flopencalphad_def.h"

void redraw() {
  printf("Redraw!\n");
  
  
  strncpy( var_calc_x ,  input_var_calc_x->value() , PATH_MAX );
  strncpy( var_calc_y ,  input_var_calc_y->value() , PATH_MAX );
  // strncpy( var_plot_x ,  input_var_plot_x->value() , PATH_MAX );
  // strncpy( var_plot_y ,  input_var_plot_y->value() , PATH_MAX );
  strncpy( var_tdb_database, input_var_tdb_database->value(), PATH_MAX );  
  
  strncpy( var_system ,      output_system->value() , PATH_MAX );
  // output_system->value( "fe c" );
  // output_system->value( var_system  );
}

Fl_Double_Window *win1=(Fl_Double_Window *)0;

static void cb_Fe(Fl_Button*, void*) {
  printf( " Fe Element Selected\n" );

// printf( "%s\n" ,   inputline->value( browser1->text(  browser1->value() )  ) ) ;

  strncat( var_system , "fe" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
  output_system->value( var_system );
  
  redraw();
}

static void cb_C(Fl_Button*, void*) {
  printf( " C Selected\n" );



  strncat( var_system , "c" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );

redraw();
}

static void cb_Mn(Fl_Button*, void*) {
  printf( " Mn Selected\n" );


  strncat( var_system , "mn" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );
    
redraw();
}

static void cb_Al(Fl_Button*, void*) {
  printf( " Al Selected\n" );


  strncat( var_system , "al" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );  

redraw();
}

static void cb_Si(Fl_Button*, void*) {
  // printf( "%s\n" ,   inputline->value( browser1->text(  browser1->value() )  ) ) ;


printf( " Si Selected\n" );

  strncat( var_system , "si" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );


redraw();
}

static void cb_V(Fl_Button*, void* v) {
  printf( " V Selected\n" );


  strncat( var_system , "v" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );

redraw();
}

static void cb_Mo(Fl_Button*, void*) {
  printf( " Mo Selected\n" );

  strncat( var_system , "mo" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );

redraw();
}

static void cb_Cr(Fl_Button*, void*) {
  printf( " Cr Selected\n" );


  strncat( var_system , "cr" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );

redraw();
}

static void cb_Cu(Fl_Button*, void*) {
  printf( " Cu Selected\n" );

  strncat( var_system , "cu" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );


redraw();
}

static void cb_Nb(Fl_Button*, void*) {
  printf( " nb Selected\n" );


  strncat( var_system , "nb" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );
    
    
redraw();
}

static void cb_Ni(Fl_Button*, void*) {
  printf( " ni Selected\n" );


  strncat( var_system , "ni" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );

redraw();
}

static void cb_Ag(Fl_Button*, void*) {
  printf( " ag Selected\n" );


  strncat( var_system , "ag" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );

redraw();
}

static void cb_Ti(Fl_Button*, void*) {
  printf( " ti Selected\n" );


  strncat( var_system , "ti" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );

redraw();
}

static void cb_Zn(Fl_Button*, void*) {
  printf( " zn Selected\n" );


  strncat( var_system , "zn" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );

redraw();
}

static void cb_W(Fl_Button*, void*) {
  printf( " w Selected\n" );


  strncat( var_system , "w" , PATH_MAX - strlen( var_system ) -1 );
  strncat( var_system , " " , PATH_MAX -  strlen( var_system ) -1 );
    output_system->value( var_system );

redraw();
}

Fl_Output *output_system=(Fl_Output *)0;

static void cb_CA(Fl_Button*, void*) {
  printf( " Clr \n" );

// printf( "%s\n" ,   inputline->value( browser1->text(  browser1->value() )  ) ) ;

   strncpy( var_system, "", PATH_MAX );
   output_system->value( var_system );  

   redraw();
}

Fl_Input *input_var_calc_x=(Fl_Input *)0;

static void cb_CA1(Fl_Button*, void*) {
  printf( " Clr \n" );

// printf( "%s\n" ,   inputline->value( browser1->text(  browser1->value() )  ) ) ;

input_var_calc_x->value( "" );

redraw();
}

Fl_Input *input_var_calc_y=(Fl_Input *)0;

static void cb_CA2(Fl_Button*, void*) {
  printf( " Clr \n" );

// printf( "%s\n" ,   inputline->value( browser1->text(  browser1->value() )  ) ) ;

input_var_calc_y->value( "" );

redraw();
}

Fl_Input *input_var_tdb_database=(Fl_Input *)0;

static void cb_CA3(Fl_Button*, void*) {
  printf( " Clr \n" );

// printf( "%s\n" ,   inputline->value( browser1->text(  browser1->value() )  ) ) ;

input_var_tdb_database->value( "" );

redraw();
}

static void cb_Quit(Fl_Button*, void*) {
  exit( 0 );
}

static void cb_3(Fl_Button*, void*) {
  char mydirnow[2500];
  printf( "Current Directory: %s \n", getcwd( mydirnow, 2500 ) );



  redraw();
  nsystem(  "  screen -d  -m   xterm -e   oc   macro.ocm " );
  
  // oc6 bug 
  // gnuplot ocgnu.plt  &;
}

static void cb_2(Fl_Button*, void*) {
  redraw();

nsystem( "  screen -d -m fledit  macro.ocm " );
}

static void cb_1(Fl_Button*, void*) {
  redraw();

clear_plot();


create_macro( );
}

static void cb_4(Fl_Button*, void*) {
  char mydirnow[2500];
  printf( "Current Directory: %s \n", getcwd( mydirnow, 2500 ) );



  redraw();
  nsystem(  "  screen -d  -m  gnuplot ocgnu.plt  " );
  
  
  // oc6 bug 
  // gnuplot ocgnu.plt  &;
}

static void cb_Option(Fl_Button*, void*) {
  win3->show();
}

static void cb_Database(Fl_Button*, void*) {
  win2->show();
}

static void cb_Plot(Fl_Button*, void*) {
  win4->show();
}

static void cb_Macro(Fl_Button*, void*) {
  win5->show();
}

Fl_Double_Window *win2=(Fl_Double_Window *)0;

Fl_Browser *browser1=(Fl_Browser *)0;

static void cb_browser1(Fl_Browser*, void*) {
  printf( "Click\n" );



 input_var_tdb_database->value(  browser1->text(   browser1->value() ) ); 
 

redraw();
}

Fl_Input *input_notes=(Fl_Input *)0;

static void cb_Add(Fl_Button*, void*) {
  browser1->add(   input_notes->value()  );

// if (  browser1->value() >= 1 )  printf( "%s\n" ,   browser1->text(  browser1->value() )  )  ;
}

static void cb_Edit(Fl_Button*, void*) {
  redraw();
  
  char charo[PATH_MAX];
  strncpy( charo, "", PATH_MAX );
  strncat( charo , " screen -d -m  fledit  " , PATH_MAX - strlen( charo ) -1 );
  strncat( charo , " " , PATH_MAX -  strlen( charo ) -1 );
  strncat( charo , " \"" , PATH_MAX -  strlen( charo ) -1 );
  strncat( charo , var_tdb_database , PATH_MAX -  strlen( charo ) -1 );
  strncat( charo , "\" " , PATH_MAX -  strlen( charo ) -1 );
  nsystem(  charo );
}

static void cb_ls(Fl_Button*, void*) {
  redraw();

  printf( "============================\n" );
  printf( "   DATABASE                 \n" );
  printf( "============================\n" );
  
  nlsgrep( ".tdb" );
  nlsgrep( ".TDB" );
}

static void cb_Elemen(Fl_Button*, void*) {
  redraw();
  
  
  printf( "============================\n" );
  printf( "   ELEMENT                  \n" );
  printf( "============================\n" );
  
  
  
  filegrep( var_tdb_database , "ELEM" );
}

static void cb_Browse(Fl_Button*, void*) {
  redraw();

  printf( "============================\n" );
  printf( "   DATABASE                 \n" );
  printf( "============================\n" );
  
  nlsgrep( ".tdb" );
  nlsgrep( ".TDB" );
  
  
  printf( "============================\n" );
  printf( "   DATABASE                 \n" );
  printf( "============================\n" );

  
        browser1->clear();
	DIR *dirp;
	struct dirent *dp;
	dirp = opendir( "." );
	while  ((dp = readdir( dirp )) != NULL ) 
	{
		if (  strcmp( dp->d_name, "." ) != 0 )
		if (  strcmp( dp->d_name, ".." ) != 0 )
                {
                    if ( ( strstr( dp->d_name, ".TDB" ) != 0 )  || ( strstr( dp->d_name, ".tdb" ) != 0 )  ) 
                    {
			printf( "%s\n", dp->d_name );
 		        browser1->add(  dp->d_name  );
 		     }
                }
	}
	closedir( dirp );
}

static void cb_Species(Fl_Button*, void*) {
  redraw();
  
  
  printf( "============================\n" );
  printf( "   SPECIES                  \n" );
  printf( "============================\n" );
  
  
  
  filegrep( var_tdb_database , "SPECIE" );
}

static void cb_Path(Fl_Button*, void*) {
  redraw();

  printf( "============================\n" );
  printf( "   PATH                     \n" );
  printf( "============================\n" );
  
    char mydirnow[2500];
  printf( "Current Directory: %s \n", getcwd( mydirnow, 2500 ) );
}

Fl_Double_Window *win3=(Fl_Double_Window *)0;

static void cb_ls1(Fl_Button*, void*) {
  nls();
}

static void cb_xterm(Fl_Button*, void*) {
  nsystem( " screen -d -m xterm " );
}

static void cb_calc(Fl_Button*, void*) {
  nsystem( " screen -d -m fl48 " );
}

static void cb_fledit(Fl_Button*, void*) {
  nsystem( " screen -d -m fledit " );
}

static void cb_ccode(Fl_Button*, void*) {
  nsystem( " screen -d -m fledit flopencalphad_def.h  " );
}

static void cb_Path1(Fl_Button*, void*) {
  redraw();

  printf( "============================\n" );
  printf( "   PATH                     \n" );
  printf( "============================\n" );
  
    char mydirnow[2500];
  printf( "Current Directory: %s \n", getcwd( mydirnow, 2500 ) );
}

static void cb_rox(Fl_Button*, void*) {
  nsystem( " rox " );
}

Fl_Double_Window *win4=(Fl_Double_Window *)0;

static void cb_Close(Fl_Button*, void*) {
  nsystem( " pkill gnuplot " );
}

Fl_Double_Window *win5=(Fl_Double_Window *)0;

Fl_Browser *browser2=(Fl_Browser *)0;

static void cb_browser2(Fl_Browser*, void*) {
  printf( "Click\n" );


 input_var_macro_filename->value(  browser2->text(   browser2->value() ) ); 


 redraw();
}

Fl_Input *input_var_macro_filename=(Fl_Input *)0;

static void cb_Browse1(Fl_Button*, void*) {
  redraw();

  printf( "============================\n" );
  printf( "   MACRO                    \n" );
  printf( "============================\n" );
  
  nlsgrep( ".ocm" );
  nlsgrep( ".OCM" );
  
   
        browser2->clear();
	DIR *dirp;
	struct dirent *dp;
	dirp = opendir( "." );
	while  ((dp = readdir( dirp )) != NULL ) 
	{
		if (  strcmp( dp->d_name, "." ) != 0 )
		if (  strcmp( dp->d_name, ".." ) != 0 )
                {
                    if ( ( strstr( dp->d_name, ".OCM" ) != 0 )  || ( strstr( dp->d_name, ".ocm" ) != 0 )  ) 
                    {
			printf( "%s\n", dp->d_name );
 		        browser2->add(  dp->d_name  );
 		     }
                }
	}
	closedir( dirp );
}

static void cb_Edit1(Fl_Button*, void*) {
  redraw();
  
  char charo[PATH_MAX];
  strncpy( charo, "", PATH_MAX );
  strncat( charo , " screen -d -m  fledit  " , PATH_MAX - strlen( charo ) -1 );
  strncat( charo , " " , PATH_MAX -  strlen( charo ) -1 );
  strncat( charo , " \"" , PATH_MAX -  strlen( charo ) -1 );
  strncat( charo , input_var_macro_filename->value() , PATH_MAX -  strlen( charo ) -1 );
  strncat( charo , "\" " , PATH_MAX -  strlen( charo ) -1 );
  nsystem(  charo );
}

static void cb_Use(Fl_Button*, void*) {
  redraw();

  printf( "============================\n" );
  printf( "   MACRO                    \n" );
  printf( "============================\n" );
  
  printf( "   FILECOPY                  \n" );
  printf( "   Source: %s                  \n" ,  input_var_macro_filename->value()   );
  printf( "   Destination: %s                  \n" ,  "macro.ocm"   );
  

  ncp( "macro.ocm" ,   input_var_macro_filename->value() );
}

Fl_Double_Window* make_window() {
  { win1 = new Fl_Double_Window(775, 700, "Notes");
    { Fl_Box* o = new Fl_Box(30, 25, 710, 30, "FLTK OpenCalphad");
      o->box(FL_ENGRAVED_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
    } // Fl_Box* o
    { Fl_Group* o = new Fl_Group(30, 85, 350, 155, "1. Element");
      o->box(FL_DOWN_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
      { Fl_Button* o = new Fl_Button(40, 95, 45, 35, "Fe");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Fe);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(100, 95, 45, 35, "C");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_C);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(160, 95, 45, 35, "Mn");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Mn);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(220, 95, 45, 35, "Al");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Al);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(280, 95, 45, 35, "Si");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Si);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(280, 185, 45, 35, "V");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_V);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(159, 140, 45, 35, "Mo");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Mo);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(100, 140, 45, 35, "Cr");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Cr);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(100, 185, 45, 35, "Cu");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Cu);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(280, 140, 45, 35, "Nb");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Nb);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(40, 140, 45, 35, "Ni");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Ni);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(40, 185, 45, 35, "Ag");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Ag);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(220, 140, 45, 35, "Ti");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Ti);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(160, 185, 45, 35, "Zn");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_Zn);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(220, 185, 45, 35, "W");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_W);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(30, 270, 350, 150, "2. Compute");
      o->box(FL_DOWN_FRAME);
      o->labeltype(FL_ENGRAVED_LABEL);
      { output_system = new Fl_Output(95, 285, 205, 25, "System");
        output_system->color(FL_BACKGROUND_COLOR);
        output_system->value( "fe c" );
      } // Fl_Output* output_system
      { Fl_Button* o = new Fl_Button(305, 285, 30, 25, "CA");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_CA);
      } // Fl_Button* o
      { input_var_calc_x = new Fl_Input(95, 315, 205, 25, "X var.");
        input_var_calc_x->value( "c" );
      } // Fl_Input* input_var_calc_x
      { Fl_Button* o = new Fl_Button(305, 315, 30, 25, "CA");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_CA1);
      } // Fl_Button* o
      { input_var_calc_y = new Fl_Input(95, 345, 205, 25, "Y var.");
        input_var_calc_y->value( "T" );
      } // Fl_Input* input_var_calc_y
      { Fl_Button* o = new Fl_Button(305, 345, 30, 25, "CA");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_CA2);
      } // Fl_Button* o
      { input_var_tdb_database = new Fl_Input(95, 375, 205, 25, "TDB");
        input_var_tdb_database->value( "steel1.tdb" );
      } // Fl_Input* input_var_tdb_database
      { Fl_Button* o = new Fl_Button(305, 375, 30, 25, "CA");
        o->labelfont(1);
        o->labelsize(12);
        o->callback((Fl_Callback*)cb_CA3);
      } // Fl_Button* o
      o->end();
      Fl_Group::current()->resizable(o);
    } // Fl_Group* o
    { Fl_Button* o = new Fl_Button(640, 650, 95, 30, "&Quit");
      o->callback((Fl_Callback*)cb_Quit);
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(30, 450, 350, 170, "3. OCM GNUPlot");
      o->box(FL_DOWN_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
      { Fl_Button* o = new Fl_Button(135, 540, 145, 25, "[&3] Compute!");
        o->callback((Fl_Callback*)cb_3);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(135, 505, 145, 25, "[&2] Edit!");
        o->callback((Fl_Callback*)cb_2);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(135, 470, 145, 25, "[&1] Create!");
        o->callback((Fl_Callback*)cb_1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(135, 575, 145, 25, "[&4] Plot!");
        o->callback((Fl_Callback*)cb_4);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Button* o = new Fl_Button(555, 650, 80, 30, "&Option");
      o->callback((Fl_Callback*)cb_Option);
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(390, 85, 345, 535, "Output");
      o->box(FL_DOWN_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->end();
    } // Fl_Group* o
    { Fl_Button* o = new Fl_Button(30, 650, 80, 30, "&Database");
      o->callback((Fl_Callback*)cb_Database);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(120, 650, 80, 30, "&Plot");
      o->callback((Fl_Callback*)cb_Plot);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(210, 650, 80, 30, "&Macro");
      o->callback((Fl_Callback*)cb_Macro);
    } // Fl_Button* o
    win1->end();
  } // Fl_Double_Window* win1
  { win2 = new Fl_Double_Window(890, 330);
    { Fl_Box* o = new Fl_Box(15, 25, 855, 35, "FLTK OpenCalphad -- Database");
      o->box(FL_ENGRAVED_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
    } // Fl_Box* o
    { Fl_Group* o = new Fl_Group(15, 95, 390, 215, "Browser");
      o->box(FL_DOWN_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
      { browser1 = new Fl_Browser(25, 110, 370, 155);
        browser1->callback((Fl_Callback*)cb_browser1);
        Fl_Group::current()->resizable(browser1);
        browser1->type(FL_HOLD_BROWSER);
      } // Fl_Browser* browser1
      { input_notes = new Fl_Input(75, 275, 165, 25, "Notes");
        input_notes->tooltip("Demo");
        input_notes->color((Fl_Color)55);
      } // Fl_Input* input_notes
      { Fl_Button* o = new Fl_Button(245, 275, 45, 25, "&Add");
        o->callback((Fl_Callback*)cb_Add);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(415, 95, 450, 215, "Database");
      o->box(FL_DOWN_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
      { Fl_Button* o = new Fl_Button(440, 115, 50, 25, "&Edit");
        o->callback((Fl_Callback*)cb_Edit);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(495, 115, 50, 25, "ls tdb");
        o->callback((Fl_Callback*)cb_ls);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(550, 115, 75, 25, "Elemen&t");
        o->callback((Fl_Callback*)cb_Elemen);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(630, 115, 70, 25, "Browse");
        o->callback((Fl_Callback*)cb_Browse);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(550, 145, 75, 25, "&Species");
        o->callback((Fl_Callback*)cb_Species);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(495, 145, 50, 25, "Path");
        o->callback((Fl_Callback*)cb_Path);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    win2->end();
    win2->resizable(win2);
  } // Fl_Double_Window* win2
  { win3 = new Fl_Double_Window(400, 210);
    { Fl_Box* o = new Fl_Box(10, 15, 380, 35, "FLTK OpenCalphad -- Option");
      o->box(FL_ENGRAVED_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
    } // Fl_Box* o
    { Fl_Group* o = new Fl_Group(20, 105, 365, 80, "System Call");
      o->box(FL_DOWN_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
      { Fl_Button* o = new Fl_Button(30, 115, 50, 25, "&ls");
        o->callback((Fl_Callback*)cb_ls1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(85, 115, 50, 25, "&xterm");
        o->callback((Fl_Callback*)cb_xterm);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(140, 115, 50, 25, "&calc");
        o->callback((Fl_Callback*)cb_calc);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(195, 115, 50, 25, "&fledit");
        o->callback((Fl_Callback*)cb_fledit);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(250, 115, 50, 25, "ccode");
        o->callback((Fl_Callback*)cb_ccode);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(305, 115, 50, 25, "Path");
        o->callback((Fl_Callback*)cb_Path1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(30, 150, 50, 25, "rox");
        o->callback((Fl_Callback*)cb_rox);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    win3->end();
    win3->resizable(win3);
  } // Fl_Double_Window* win3
  { win4 = new Fl_Double_Window(845, 370);
    { Fl_Box* o = new Fl_Box(20, 25, 800, 35, "FLTK OpenCalphad -- Plot");
      o->box(FL_ENGRAVED_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
    } // Fl_Box* o
    { Fl_Group* o = new Fl_Group(20, 105, 800, 220, "Plot");
      o->box(FL_DOWN_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
      { Fl_Button* o = new Fl_Button(30, 115, 90, 25, "Close &Plots");
        o->callback((Fl_Callback*)cb_Close);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    win4->end();
  } // Fl_Double_Window* win4
  { win5 = new Fl_Double_Window(885, 345);
    { Fl_Box* o = new Fl_Box(30, 15, 830, 35, "FLTK OpenCalphad -- Macro");
      o->box(FL_ENGRAVED_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
    } // Fl_Box* o
    { Fl_Group* o = new Fl_Group(25, 110, 390, 215, "Browser");
      o->box(FL_DOWN_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
      { browser2 = new Fl_Browser(35, 125, 370, 155);
        browser2->callback((Fl_Callback*)cb_browser2);
        Fl_Group::current()->resizable(browser2);
        browser2->type(FL_HOLD_BROWSER);
      } // Fl_Browser* browser2
      { input_var_macro_filename = new Fl_Input(95, 290, 310, 25, "Filename");
      } // Fl_Input* input_var_macro_filename
      o->end();
    } // Fl_Group* o
    { Fl_Group* o = new Fl_Group(430, 110, 430, 215, "Macro");
      o->box(FL_DOWN_BOX);
      o->labeltype(FL_ENGRAVED_LABEL);
      { Fl_Button* o = new Fl_Button(450, 130, 70, 25, "Browse");
        o->callback((Fl_Callback*)cb_Browse1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(530, 130, 50, 25, "&Edit");
        o->callback((Fl_Callback*)cb_Edit1);
      } // Fl_Button* o
      { Fl_Button* o = new Fl_Button(590, 130, 100, 25, "&Use macro");
        o->callback((Fl_Callback*)cb_Use);
      } // Fl_Button* o
      o->end();
    } // Fl_Group* o
    win5->end();
    win5->resizable(win5);
  } // Fl_Double_Window* win5
  return win5;
}

void addkeypress( int keypress ) {
  //char str[PATH_MAX]; 
     //snprintf( str , sizeof( str ), "%s%c", inputline->value() , keypress ); 
     //inputline->value( str  );
}

int main( int argc, char *argv[]) {
  // working dir 
    if ( argc == 2)
    if ( strcmp( argv[1] , "" ) !=  0 )
    {
            chdir( argv[ 1 ] );
    }
    
    char mydirnow[2500];
    printf( "Current Directory: %s \n", getcwd( mydirnow, 2500 ) );
  
    // vars
    strncpy( var_system, "", PATH_MAX);
    
  
    make_window();
    win1->show();
  
    Fl::run();
}
