// generated by Fast Light User Interface Designer (fluid) version 1.0305

#ifndef flopencalphad_h
#define flopencalphad_h
#include <FL/Fl.H>
void redraw();
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win1;
#include <FL/Fl_Box.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Output.H>
extern Fl_Output *output_system;
#include <FL/Fl_Input.H>
extern Fl_Input *input_var_calc_x;
extern Fl_Input *input_var_calc_y;
extern Fl_Input *input_var_tdb_database;
#include <FL/Fl_Browser.H>
extern Fl_Browser *flfront_preview_browser1;
extern Fl_Double_Window *win2;
#include <FL/Fl_Tabs.H>
#include <FL/Fl_File_Browser.H>
extern Fl_File_Browser *form_database_tab1_filebrowser1;
extern Fl_Output *form_database_tab1_currentfile;
extern Fl_Input *form_database_tab1_filter;
extern Fl_Browser *browser1;
extern Fl_Input *input_notes;
extern Fl_Input *form_database_fetch_url;
extern Fl_Double_Window *win3;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *checkbutton_single_console;
extern Fl_Check_Button *checkbutton_xterm_console;
extern Fl_Double_Window *win4;
extern Fl_Output *form_plot_statusline;
extern Fl_Check_Button *plot_adv_computer_skipint;
extern Fl_Input *var_x_advplot_str;
extern Fl_Input *var_y_advplot_str;
extern Fl_Check_Button *var_button_y_advplot_str_automatic;
extern Fl_Browser *flplot_preview_browser;
extern Fl_Input *plot_gnuplot_term_drivername;
extern Fl_Check_Button *plot_gnuplot_term_driver_force;
extern Fl_Double_Window *win5;
extern Fl_Browser *browser2;
extern Fl_Input *input_var_macro_filename;
extern Fl_Browser *browser_macro_filecontent;
extern Fl_Double_Window *win6;
extern Fl_Input *input_var_set_condition;
extern Fl_Input *input_var_calc_ymin;
extern Fl_Input *input_var_calc_ymax;
extern Fl_Input *input_var_calc_ystep;
extern Fl_Input *input_var_calc_xmin;
extern Fl_Input *input_var_calc_xmax;
extern Fl_Double_Window *win7;
extern Fl_Input *dev_path_input1;
extern Fl_Check_Button *var_calc_rm_ocgnu;
extern Fl_Double_Window *form_element_pse;
extern Fl_Double_Window *form1_periodic_information;
extern Fl_Browser *form_content_browser1;
Fl_Double_Window* make_window();
void addkeypress( int keypress );
int main( int argc, char *argv[] );
void void_flfront_preview_browser1_refresh();
void void_plot_preview_plotfile( const  char *foopatfile  );
int ncopysetterm( const char *foofileout,  const  char *foofilein, const  char *fooxdriver  );
void load_content( int fooz );
void void_form_add_new_element( const char *foonew );
#endif
