// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef flprintfile_h
#define flprintfile_h
#include <FL/Fl.H>
void redraw();
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win1;
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_File_Browser.H>
extern Fl_File_Browser *browser;
#include <FL/Fl_Output.H>
extern Fl_Output *output_curfile;
extern Fl_Output *output_curdir;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *filefilter;
#include <FL/Fl_Input.H>
extern Fl_Input *filefilterstr;
Fl_Double_Window* make_window();
int main( int argc, char *argv[]);
#endif
