// generated by Fast Light User Interface Designer (fluid) version 1.0304

#include "flview.h"
#include <stdio.h>
#include <stdlib.h>
#include "ccode.h"
static char user_arg1[PATH_MAX]; 

void loadpanel( const char *pattern ) {
  printf("Load Panel!\n");
  
  
    
    int fetchi;
    FILE *fp5;
    FILE *fp6;
    char fetchline[PATH_MAX];
    char fetchlinetmp[PATH_MAX];
  
      fbrow->clear( );    
      
      fp6 = fopen( pattern , "rb");
      while( !feof(fp6) ) 
      {
            fgets(fetchlinetmp, PATH_MAX, fp6); 
            strncpy( fetchline, "" , PATH_MAX );
            for( fetchi = 0 ; ( fetchi <= strlen( fetchlinetmp ) ); fetchi++ )
              if ( fetchlinetmp[ fetchi ] != '\n' )
                   fetchline[fetchi]=fetchlinetmp[fetchi];
                   
                  if ( !feof( fp6 ) ) 
                  {
                   fbrow->add( fetchline );    
                  }
  
       }
       fclose( fp6 );
}

Fl_Double_Window *win1=(Fl_Double_Window *)0;

static void cb_Cancel(Fl_Button*, void*) {
  exit( 0 );
}

static void cb_Load(Fl_Button*, void*) {
  loadpanel( user_arg1 );
}

Fl_Browser *fbrow=(Fl_Browser *)0;

Fl_Double_Window* make_window() {
  { win1 = new Fl_Double_Window(875, 655);
    { Fl_Button* o = new Fl_Button(735, 625, 135, 25, "&Cancel");
      o->labelfont(1);
      o->callback((Fl_Callback*)cb_Cancel);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(595, 625, 135, 25, "&Load");
      o->callback((Fl_Callback*)cb_Load);
    } // Fl_Button* o
    { fbrow = new Fl_Browser(25, 25, 825, 585);
      fbrow->type(FL_HOLD_BROWSER);
    } // Fl_Browser* fbrow
    win1->end();
    win1->resizable(win1);
  } // Fl_Double_Window* win1
  return win1;
}

int main( int argc, char *argv[]) {
  printf( " == FLVIEW == \n" );
  
    char mydirnow[2500];
    printf( "Current Directory: %s \n", getcwd( mydirnow, 2500 ) );
   
    char filein[PATH_MAX];
    char filesource[PATH_MAX];
    strncpy( filesource , "/etc/hostname" , PATH_MAX );
    strncpy( filein ,     filesource , PATH_MAX );
    if ( argc == 2)
    if ( strcmp( argv[1] , "" ) !=  0 ) 
    {
            strncpy( filein, argv[ 1 ], PATH_MAX );
            strncpy( filesource , argv[ 1 ], PATH_MAX );
    }
    strncpy( user_arg1, filein , PATH_MAX );
   
    make_window();
    
    loadpanel(   filein   );
    
    win1->show();
    Fl::run();
}
