// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef flxrandr_h
#define flxrandr_h
#include <FL/Fl.H>
void loadpanel( const char *pattern );
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win1;
#include <FL/Fl_Button.H>
#include <FL/Fl_Browser.H>
extern Fl_Browser *fbrow;
#include <FL/Fl_Box.H>
Fl_Double_Window* make_window();
int main( int argc, char *argv[]);
#endif
