// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef fxgrapher_h
#define fxgrapher_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win1;
#include <FL/Fl_Box.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Input.H>
extern Fl_Input *form1_tab1_grapher_plot_filesource;
#include <FL/Fl_Button.H>
extern Fl_Input *form1_tab1_grapher_function_fx;
extern Fl_Input *form1_tab1_grapher_function_gx;
extern Fl_Input *form1_tab1_grapher_function_hx;
#include <FL/Fl_Check_Button.H>
extern Fl_Check_Button *fx_check_active_fx;
extern Fl_Check_Button *fx_check_active_gx;
extern Fl_Check_Button *fx_check_active_hx;
extern Fl_Input *form1_tab1_grapher_xrange;
extern Fl_Input *form1_tab1_grapher_yrange;
extern Fl_Check_Button *fxgrapher_mode_x11_driver_on;
#include <FL/Fl_Browser.H>
extern Fl_Browser *browser1;
extern Fl_Input *fxgrapher_calcpad_formula1;
extern Fl_Browser *browser2;
extern Fl_Input *input_var_macro_filename;
extern Fl_Browser *browser_macro_filecontent;
extern Fl_Browser *tab5_browser2;
extern Fl_Input *tab5_input_var_macro_filename;
extern Fl_Browser *tab5_browser_macro_filecontent;
extern Fl_Input *tab5_dataplot_colx;
extern Fl_Input *tab5_dataplot_coly;
extern Fl_Check_Button *tab5_dataplot_mode_x11_driver_on;
extern Fl_Input *tab6_form1_tab1_grapher_xrange;
extern Fl_Input *tab6_form1_tab1_grapher_yrange;
extern Fl_Check_Button *tab5_dataplot_mode_console_plot_on;
extern Fl_Check_Button *tab5_dataplot_mode_console_plot_scale_on;
extern Fl_Input *tab7_dataplot_colx;
extern Fl_Input *tab7_dataplot_coly;
extern Fl_Input *tab7_form1_x_min;
extern Fl_Input *tab7_form1_x_max;
extern Fl_Input *tab7_form1_x_step;
extern Fl_Input *tab7_form1_func_f1;
extern Fl_Input *tab7_form1_func_f2;
extern Fl_Check_Button *tab7_dataplot_mode_x11_driver_on;
extern Fl_Input *tab7_form1_tab1_grapher_xrange;
extern Fl_Input *tab7_form1_tab1_grapher_yrange;
extern Fl_Input *tab7_input_var_macro_filename;
extern Fl_Input *tab7_form1_tab1_grapher_plot_header;
extern Fl_Input *tab7_form1_func_f3;
extern Fl_Check_Button *tab7_form1_func_f3_button_checker;
extern Fl_Browser *tab3_browser2;
#include <FL/Fl_Output.H>
extern Fl_Output *win1_statusbar_content;
Fl_Double_Window* make_window();
int main( int argc, char *argv[]);
void calc_ecalc_enter();
#endif
