// generated by Fast Light User Interface Designer (fluid) version 1.0304

#ifndef fxrun_h
#define fxrun_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *win3;
#include <FL/Fl_Box.H>
#include <FL/Fl_Input.H>
extern Fl_Input *input_open;
#include <FL/Fl_Check_Button.H>
#include <FL/Fl_Button.H>
Fl_Double_Window* make_window();
int main();
#endif
